max_worker_number=2

[[job]]
version = "1.24"
image = "alpine"
name = "test1"
command = "sleep 10"
interval = "60s"

[[job]]
version = "1.24"
image = "alpine"
name = "test2"
command = "echo hello world"
interval = "60s"

[job_log]
type = "redis"
redis_addr = "localhost:6379"
redis_key = "logstash-job"

[status_server]
listen = ""
port = "3000"