version: '2'
services:
  tjmsync:
    image: yezersky/tjmsync
    ports:
      - "3000:3000"
    volumes:
      - ./conf/tjmsync.toml:/etc/tjmsync.toml
      - ${HOST_MIRROR_DIR}:${TJMSYNC_MIRROR_DIR}
  nginx:
    image: nginx:1.11
    ports:
      - "8000:80"
    volumes:
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ${HOST_MIRROR_DIR}:/usr/share/nginx/html
  apache:
    image: httpd:2.4
    ports:
      - "8010:80"
    volumes:
      - ./conf/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ${HOST_MIRROR_DIR}:/usr/local/apache2/htdocs
  caddy:
    image: abiosoft/caddy
    ports:
      - "8020:80"
    volumes:
      - ./conf/caddy:/etc/caddy
      - ${HOST_MIRROR_DIR}:/var/www
    command: ["--conf", "/etc/caddy/Caddyfile", "--log", "stdout"]